import { Task } from "@/types";

export const mockTasks: Task[] = [
  {
    id: "1",
    title: "Watch Tech Review Video",
    description: "Watch this 5-minute tech product review",
    videoUrl: "",
    campaignId: "1",
    reward: 85,
    duration: 5,
    completions: 234,
    status: "active",
    createdAt: new Date(),
  },
  {
    id: "2",
    title: "Music Video - Pop Hit",
    description: "Watch latest music video release",
    videoUrl: "",
    campaignId: "2",
    reward: 85,
    duration: 4,
    completions: 567,
    status: "active",
    createdAt: new Date(),
  },
  {
    id: "3",
    title: "Gaming Highlights",
    description: "Watch gaming stream highlights",
    videoUrl: "",
    campaignId: "3",
    reward: 85,
    duration: 6,
    completions: 123,
    status: "active",
    createdAt: new Date(),
  },
  {
    id: "4",
    title: "Travel Vlog",
    description: "Watch travel adventure video",
    videoUrl: "",
    campaignId: "4",
    reward: 85,
    duration: 7,
    completions: 89,
    status: "active",
    createdAt: new Date(),
  },
];